apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\PIPE\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert -f docker-compose.yaml
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: delete
  name: delete
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: delete
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\PIPE\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert -f docker-compose.yaml
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/final-docker-default: "true"
        io.kompose.service: delete
    spec:
      containers:
        - env:
            - name: SPRING_DATASOURCE_PASSWORD
              value: root
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/DockerCRUD
            - name: SPRING_DATASOURCE_USERNAME
              value: root
          image: pipe0427/delete
          name: delete
          ports:
            - containerPort: 8084
              hostPort: 8084
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
